version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my_home_server_db
    restart: always
    environment:
      POSTGRES_DB: home_server_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
