version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my_home_server_db
    restart: always
    environment:
      POSTGRES_DB: home_server_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "0.0.0.0:8080:80"  # This binds to all network interfaces
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # Add these to ensure proper hosting
      - ASPNETCORE_HOSTNAME=0.0.0.0
      - ASPNETCORE_HTTP_PORTS=80
    networks:
      - app-network
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

